# Site settings
title: Code Me Curtis
subtitle: The DBC & More Journey
email: infin80design@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is for future employers to see my growth throughout Dev Bootcamp and beyond.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: codemecurtis
github_username:  infin80design

paginate: 7
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
